# default to true for all rules
default: true

# MD007/unordered-list-indent
MD007:
  indent: 4

# MD033/no-inline-html
MD033: false

# MD013/line-length
MD013:
  code_block_line_length: 80
  code_blocks: true
  heading_line_length: 80
  headings: true
  line_length: 80
  stern: false
  strict: false
  tables: true

# MD014/commands-show-output
MD014: false

# MD024/no-duplicate-heading
MD024:
  # Allow when nested under different parents e.g. CHANGELOG.md
  siblings_only: true

# MD046/code-block-style
#
# Ignore this because it conflicts with the code block style used in content
# tabs of mkdocs-material which is to add a blank line after the content title.
#
# Ref: https://github.com/astral-sh/ruff/pull/15011#issuecomment-2544790854
MD046: false

# Link text should be descriptive
# Disallows link text like *here* which is annoying.
MD059: false
