"$schema": "https://json.schemastore.org/prettierrc"
"tabWidth": 2
"singleQuote": false
"quoteProps": "consistent"
"trailingComma": "all"
"proseWrap": "always"
"endOfLine": "lf"
"embeddedLanguageFormatting": "auto"
