[package]
name = "cowsay-interpreter"
description = "Cowfile interpreter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
readme.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]

[dev-dependencies]
pretty_assertions = { workspace = true }

[lints]
workspace = true
